# Generated by Django 4.1.7 on 2023-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('finalizado', models.BooleanField()),
                ('resenha', models.CharField(max_length=450)),
            ],
        ),
    ]
